services:
  headscale:
    container_name: headscale
    image: headscale/headscale:latest
    restart: unless-stopped
    volumes:
      - /home/docker/headscale/config:/etc/headscale
      - /home/docker/headscale/keys:/var/lib/headscale
    environment:
      - HEADSCALE_SERVER_URL=http://188.68.50.114:8080  # Change if needed
      - HEADSCALE_DB_TYPE=sqlite
      - HEADSCALE_DB_PATH=/var/lib/headscale/db.sqlite
    command: serve  # Make sure this line is correct
    ports:
      - 8080:8080  # Change if needed

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    container_name: headscale-ui
    restart: unless-stopped
    ports:
        - 9999:80cd 

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
       - /home/docker/portainer/data:/data
       - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped